In [1]:
!pip install pandas numpy scikit-learn nltk streamlit matplotlib seaborn wordcloud joblib

Requirement already satisfied: pandas in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.2)
Requirement already satisfied: numpy in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.4.4)
Requirement already satisfied: scikit-learn in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.8.0)
Requirement already satisfied: nltk in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.9.4)
Requirement already satisfied: streamlit in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.57.0)
Requirement already satisfied: matplotlib in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.10.9)
Requirement already satisfied: seaborn in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (0.13.2)
Requirement already satisfied: wordcloud in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.9.6)
Requirement already satisfied: joblib in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\asus\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: threadpoolctl>=3.2.0 in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: click in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from nltk) (8.3.3)
Requirement already satisfied: regex>=2021.8.3 in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from nltk) (2026.5.9)
Requirement already satisfied: tqdm in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from nltk) (4.67.3)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (6.1.0)
Requirement already satisfied: blinker<2,>=1.5.0 in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (7.1.1)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (3.1.50)
Requirement already satisfied: packaging>=20 in C:\Users\asus\AppData\Roaming\Python\Python314\site-packages (from streamlit) (26.2)
Requirement already satisfied: pillow<13,>=7.1.0 in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (12.2.0)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (0.9.2)
Requirement already satisfied: protobuf<8,>=3.20 in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (6.33.6)
Requirement already satisfied: pyarrow>=7.0 in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (24.0.0)
Requirement already satisfied: requests<3,>=2.27 in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (2.33.1)
Requirement already satisfied: tenacity<10,>=8.1.0 in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (4.15.0)
Requirement already satisfied: starlette>=0.40.0 in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (1.0.0)
Requirement already satisfied: uvicorn>=0.30.0 in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (0.46.0)
Requirement already satisfied: httptools>=0.6.3 in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (0.7.1)
Requirement already satisfied: anyio>=4.0.0 in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (4.13.0)
Requirement already satisfied: python-multipart>=0.0.10 in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (0.0.27)
Requirement already satisfied: websockets>=12.0.0 in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (16.0)
Requirement already satisfied: itsdangerous>=2.1.2 in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=2.4.0 in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.20.0)
Requirement already satisfied: colorama in C:\Users\asus\AppData\Roaming\Python\Python314\site-packages (from click->nltk) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests<3,>=2.27->streamlit) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests<3,>=2.27->streamlit) (3.13)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests<3,>=2.27->streamlit) (1.26.20)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests<3,>=2.27->streamlit) (2026.4.22)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.30.0)
Requirement already satisfied: six>=1.5 in C:\Users\asus\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: h11>=0.8 in C:\Users\asus\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from uvicorn>=0.30.0->streamlit) (0.16.0)

In [2]:
import pandas as pd
import numpy as np
import re
import joblib

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [3]:
fake = pd.read_csv("../data/Fake.csv") # Fake haber datasetini okur.
true = pd.read_csv("../data/True.csv") # Gerçek haber datasetini okur.

In [4]:
fake["label"] = 0  # Fake haberlere etiket verir.
true["label"] = 1  # Gerçek haberlere etiket verir.

In [5]:
df = pd.concat([fake, true], axis=0) # İki dataframe’i alt alta birleştirir.

In [6]:
df = df.sample(frac=1, random_state=42) # Verileri karıştırır.

In [7]:
df.reset_index(drop=True, inplace=True) # Karıştırmadan sonra indexleri sıfırlar.

df.info() Şunları gösterir:

* sütun isimleri
* veri tipleri
* boş veri var mı

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 44898 entries, 0 to 44897
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    44898 non-null  str
 1   text     44898 non-null  str
 2   subject  44898 non-null  str
 3   date     44898 non-null  str
 4   label    44898 non-null  int64
dtypes: int64(1), str(4)
memory usage: 112.3 MB

In [9]:
df.isnull().sum() # Her sütunda kaç boş veri olduğunu gösterir.

title      0
text       0
subject    0
date       0
label      0
dtype: int64

In [10]:
df.dropna(inplace=True) # Boş satırları siler.

In [11]:
df.duplicated().sum() # Kaç tane tekrar eden veri var gösterir.

np.int64(209)

In [12]:
df.drop_duplicates(inplace=True) # Tekrarlayan haberleri kaldırır.

In [13]:
df.shape # Kaç satır ve sütun olduğunu gösterir.

(44689, 5)

In [14]:
def clean_text(text): # Metni temizleyen fonksiyon.

    text = str(text).lower() # Bütün harfleri küçültür.

    # url kaldır
    text = re.sub(r"http\S+", "", text) # Linkleri kaldırır.

    # www kaldır
    text = re.sub(r"www\S+", "", text)

    # html tag kaldır
    text = re.sub(r"<.*?>", "", text)

    # noktalama kaldır
    text = re.sub(r"[^\w\s]", "", text)

    # fazla boşluk kaldır
    text = re.sub(r"\s+", " ", text).strip() # Birden fazla boşluğu temizler.

    return text

In [15]:
df["clean_text"] = df["text"].apply(clean_text) # Temizlenmiş metni yeni sütuna yazar.

In [16]:
df[["text", "clean_text"]].head() # Orijinal ve temizlenmiş metni karşılaştırır.

,text,clean_text
0,"21st Century Wire says Ben Stein, reputable pr...",21st century wire says ben stein reputable pro...
1,WASHINGTON (Reuters) - U.S. President Donald T...,washington reuters us president donald trump r...
2,(Reuters) - Puerto Rico Governor Ricardo Rosse...,reuters puerto rico governor ricardo rossello ...
3,"On Monday, Donald Trump once again embarrassed...",on monday donald trump once again embarrassed ...
4,"GLASGOW, Scotland (Reuters) - Most U.S. presid...",glasgow scotland reuters most us presidential ...

In [17]:
import nltk

In [18]:
nltk.download("stopwords") # İngilizce anlamsız kelimeleri indirir.

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\asus\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [19]:
from nltk.corpus import stopwords

In [20]:
stop_words = set(stopwords.words("english")) # İngilizce gereksiz kelimeleri alır.

In [21]:
def remove_stopwords(text): # Anlamsız kelimeleri kaldırır.

    words = text.split() # Cümleyi kelimelere böler.

    filtered_words = [  # Stopword olmayanları bırakır.
        word for word in words
        if word not in stop_words
    ]

    return " ".join(filtered_words) # Kelimeleri tekrar cümle yapar.

In [22]:
df["clean_text"] = df["clean_text"].apply(remove_stopwords) # Temizleme işlemini tüm veriye uygular.

In [23]:
df[["text", "clean_text"]].head()

,text,clean_text
0,"21st Century Wire says Ben Stein, reputable pr...",21st century wire says ben stein reputable pro...
1,WASHINGTON (Reuters) - U.S. President Donald T...,washington reuters us president donald trump r...
2,(Reuters) - Puerto Rico Governor Ricardo Rosse...,reuters puerto rico governor ricardo rossello ...
3,"On Monday, Donald Trump once again embarrassed...",monday donald trump embarrassed country accide...
4,"GLASGOW, Scotland (Reuters) - Most U.S. presid...",glasgow scotland reuters us presidential candi...

In [24]:
nltk.download("wordnet")
nltk.download("omw-1.4")

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\asus\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\asus\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [25]:
from nltk.stem import WordNetLemmatizer

In [26]:

lemmatizer = WordNetLemmatizer() # Kelime kökü bulma aracı.

In [27]:
def lemmatize_text(text): # Kelimeleri kök haline çevirir.

    words = text.split()

    lemmatized_words = [
        lemmatizer.lemmatize(word)
        for word in words
    ]

    return " ".join(lemmatized_words)

In [28]:
df["clean_text"] = df["clean_text"].apply(lemmatize_text) # Tüm dataset’e uygular.

In [29]:
df[["text", "clean_text"]].head()

,text,clean_text
0,"21st Century Wire says Ben Stein, reputable pr...",21st century wire say ben stein reputable prof...
1,WASHINGTON (Reuters) - U.S. President Donald T...,washington reuters u president donald trump re...
2,(Reuters) - Puerto Rico Governor Ricardo Rosse...,reuters puerto rico governor ricardo rossello ...
3,"On Monday, Donald Trump once again embarrassed...",monday donald trump embarrassed country accide...
4,"GLASGOW, Scotland (Reuters) - Most U.S. presid...",glasgow scotland reuters u presidential candid...

In [30]:
df["text_length"] = df["clean_text"].apply(lambda x: len(x.split())) # Her haberin kaç kelime olduğunu hesaplar.

df["text_length"].describe() Şunları verir:

* ortalama
* min
* max
* standart sapma

In [31]:
df["text_length"].describe()

count    44689.000000
mean       233.022981
std        203.499615
min          0.000000
25%        118.000000
50%        205.000000
75%        292.000000
max       4920.000000
Name: text_length, dtype: float64

In [32]:
df = df[df["text_length"] > 5] # 5 kelimeden kısa haberleri kaldırır.

In [33]:
df.shape # Temizlik sonrası veri boyutunu gösterir.

(43822, 7)

In [34]:
df.to_csv("../data/cleaned_news.csv", index=False) # Temizlenmiş veriyi CSV olarak kaydeder.